### ISSUE TITLE
[Ubuntu Linux] Crashes on Save

### ISSUE THREAD

**Issue by ENDev15** [careteditor/caret#67] opened 2016-05-02 00:51 UTC
Today when I tried to save a Markdown files, Caret crashed. Upon trying again, I found that Caret had saved the file but removed all of the data. I then tested this on other files, and found that whenever I saved a file, the file would be made blank. Caret did not always crash, however.

This was not happening before, so I am not sure what's going on. At the same time, I noticed that all of the options in the **Help** menu give an error. 

Thanks for your hard work.

**Comment by erusev** [comment] 2016-05-02 07:58
Thanks, we'll see what we can do.

**Comment by huwd** [comment] 2016-05-05 10:43
I can confirm I've got the same issue. Lost the same file twice :(

Alas, beta software - comes with the territory, eh?

 Been trying to work out how to get you a dump out of Ubuntu - it does seem to trigger Ubuntu's internal crash logger... but as it's a third party package I don't think that report will get auto sent anywhere useful...

The title is "Caret crashed with SIGABRT in node::Buffer::CallbackInfo::Callbackinfo()

Really frustratingly I can't copy paste the stacktrace out of the Ubuntu window... @ENDev15 as another Ubuntu user, you got any idea how to do that?

Anyway here's a screenshot (really not ideal of the stacktrace top) hope there's something useful in there.
![stacktrace-caret-crash-ubuntu](https://cloud.githubusercontent.com/assets/3694062/15041782/902d58ca-12b6-11e6-93f5-e0b4dad30e8a.jpg)

**Comment by erusev** [comment] 2016-05-05 12:56
Thanks for the detailed feedback, @huwd!

Does this happen every time you save?

Thanks again.

**Comment by huwd** [comment] 2016-05-06 08:43
@erusev no, i have had successful saves - I've not fully tested for reproducibility - but generally it seems like I've sat down - saved a few (perhaps 2/3?) times across a session and then on the final save caret has crashed and when I open the file in another text editor there is nothing inside.

Only only thing was that I got a warning much earlier in the session that something had gone wrong and would I like to report it to github (error message from within caret), everything still seemed to be working through so I carried on. Not sure if my final save was since seeing that message, will test and see if I can reproduce.

Anyone got any advice on how to get a full debug trace from crashes on ubuntu? Guessing ideally you'd wanna see what node/electron were doing at the time of the crash?

**Comment by astoilkov** [comment] 2016-05-06 09:08
Hi @huwd,

Next time the application crashes you could zip and send us the contents of the `~/.config/Caret/caret` folder.

Thanks

**Comment by erusev** [comment] 2016-05-06 10:29
Thanks @huwd for the detailed response! 

You can send the zip that @astoilkov mentioned to contact@caret.io - it would also help us with #65 - could you, please, disable dark mode and send us the zip (regardless of weather the app crashed) so that we can see if disabling dark mode fails to make the correct changes in the configuration files of the app to cause #65.

Thanks.

**Comment by huwd** [comment] 2016-05-07 11:44
Sure will give it a go today

**Comment by astoilkov** [comment] 2016-06-04 18:59
This issue should be fixed in the latest Caret release. Can some of you try if it can still be replicated.

Thanks in advance.

**Comment by huwd** [comment] 2016-06-05 11:35
Amazing, will run a few tests today.

**Comment by ENDev15** [comment] 2016-06-05 14:57
Thanks! Seems to be working properly now, though I could not test it extensively. Sorry I couldn't get a detailed crash report to you originally, completely forgot about it.

**Comment by astoilkov** [comment] 2016-06-05 15:26
Perfect. Happy to hear that. Closing the issue. If it appears again don't hesitate to reopen it again.

Have a nice day.

**Closed by astoilkov** 2016-06-05 15:26 UTC
Labels: bug, priority

**Comment by huwd** [comment] 2016-06-10 10:07
I second that - also not had  a chance to test extensively but for the many snippets here and there it's been far more stable - many thanks
