### ISSUE TITLE
Caret get stuck when opening files via Ctrl+T / Ctrl+E

### ISSUE THREAD

**Issue by ramthir** [careteditor/caret#513] opened 2017-08-23 07:34 UTC
Very frequently Caret (3.4.5) gets stuck when opening files via Ctrl+T / Ctrl+E. When this happens I have to forcefully quit Caret and start again.

**Comment by erusev** [comment] 2017-08-23 08:14
Do you think this issue existed in earlier versions?

Thanks!

**Comment by ramthir** [comment] 2017-08-23 11:02
1. I'm on Windows 10. 
2. I've started using Caret recently so I'm not sure if it's a new issue or not.

**Comment by astoilkov** [comment] 2017-08-23 11:21
Hi @ramthir,

We suspect that the issue is caused by some specific files that are causing the problem upon opening them. Is it possible to send a file which when opened from Ctrl+T makes Caret get stuck?

Thanks in advance.

**Comment by astoilkov** [comment] 2017-08-25 09:02
We think we found the reason for the problem. You could update Caret and the issue should be fixed.

Closing this issue. If the problem happens again don't hesitate to write here.

**Closed by astoilkov** 2017-08-25 09:02 UTC
Labels: bug, resolved

**Comment by ramthir** [comment] 2017-08-29 04:21
Yeap! I got the update and the issue is fixed...
