### ISSUE TITLE
Wrong react with Chinese input

### ISSUE THREAD

**Issue by massacreformash** [careteditor/caret#244] opened 2017-02-19 16:07 UTC
When I use Chinese input method, the caret was keeping jump up and down between the top of window and the line that I inputed. It's really annoying and I cannot typing anymore.

Which ever Chinese input method I used with imagine function has the same issue. The mac built-in is also has this issue.

Please fix it.

**Comment by massacreformash** [comment] 2017-02-19 16:15
![jumping caret](https://drops.azureedge.net/drops/files/acc_502429/Gqtm?rscd=inline%3B%20filename%3DScreen%2520Capture%2520on%25202017-02-20%2520at%252000-13-43.gif&rsct=image%2Fgif&se=2017-02-19T16%3A44%3A20Z&sig=ophMtYu725xrztLAp1o9kp8BcOK626dxtZJam0FkUY0%3D&sp=r&sr=b&st=2017-02-19T15%3A44%3A20Z&sv=2013-08-15)

**Comment by astoilkov** [comment] 2017-02-19 16:28
We are immediately starting to work on this. Thanks for reporting.

**Comment by astoilkov** [comment] 2017-02-23 16:12
Hi @massacreformash,

We found the cause of the problem. It seems this is a Chromium bug in the latest version. I can consistently replicate the bug in latest Chrome in GitHub even. We will log it there and post the issue here so we can track it's progress.

Sorry for any inconvenience caused.

**Comment by astoilkov** [comment] 2017-02-27 11:38
We reported the bug to Chromium team. You could follow it's progress from [here](https://bugs.chromium.org/p/chromium/issues/detail?id=696492).

**Comment by massacreformash** [comment] 2017-02-28 07:47
Thanks for still working on this issue! 
I found that they has fixed it on M57. So what should I do to fix this properly? Or just wait for your team to fix it?

**Comment by astoilkov** [comment] 2017-02-28 07:49
The next step is for Electron to release a version containing M57. When this is done we could immediately create a patch release with the fix included.

You could follow Electron release progress [here](https://github.com/electron/electron/releases).

**Comment by massacreformash** [comment] 2017-04-24 09:19
Still has this problem. Other way to fix it?

**Comment by massacreformash** [comment] 2017-06-26 07:13
I am not sure if my environment was broken or some preference settings was wrong, on my newest macOS 10.12.5 (Macbook Pro 15' late 2013), this issue still happens.
I have taken a screenshot of this problem.

![http://d.pr/i/QU9zAJ+]()

**Comment by astoilkov** [comment] 2017-06-28 12:21
Hi @massacreformash,

We think we fixed the problem in Caret 3.0.2. Can you update and check?

Sorry for the delay. The issue was labeled as resolved because we fixed it in our internal builds but haven't release a version since then. Caret 3 brought all fixes we did a while time ago.

**Comment by astoilkov** [comment] 2017-07-11 19:59
I am closing this issue as it seems fixed. If anyone still experiences the issue we can reopen it.

**Closed by astoilkov** 2017-07-11 19:59 UTC
Labels: bug, resolved
