### ISSUE TITLE
PDF export font size

### ISSUE THREAD

**Issue by instanceofme** [careteditor/caret#107] opened 2016-09-05 15:05 UTC
Two things about it:
1. It depends on the _editor_'s font size: if you have your edit in "small size" setting, the PDF will have smaller text than if you have your editor in regular font size.
2. I couldn't override it in the theme CSS file. Adding `html { font-size: 18px !important; }` does not change it. Typical use case: the whole theme CSS is set in `rem`s to easily compose vertical rhythm.

**Comment by erusev** [comment] 2016-09-05 18:24
Thanks @instanceofme, makes sense, we'll see what we can do.

**Comment by astoilkov** [comment] 2016-09-13 13:52
Hi @instanceofme,

Could share you app version? I was testing the latest version of Caret 1.5.4 where the PDF font size is fixed to 14px.

Thanks in advance.

**Comment by instanceofme** [comment] 2016-09-14 17:04
My bad, the actual text font-size sees to be the same, but not the `font-size` for `html`, which is used by `rem` units.

Examples with `.preview { line-height: 1.75rem; }`:
- [Medium size selected](https://github.com/careteditor/caret/files/472741/2016-09-14-m.pdf)
- [Small size selected](https://github.com/careteditor/caret/files/472742/2016-09-14.pdf)

**Comment by astoilkov** [comment] 2016-10-26 07:31
We have now fixed the issue. The generated PDF will always be the same regardless of the application font-size. I will close this issue when we release the next version which will include the change.

Sorry for the late response.

**Comment by astoilkov** [comment] 2016-11-21 08:50
This is now available in the latest Caret 1.9.1 release.

Closing this.

**Comment by instanceofme** [comment] 2016-11-21 10:43
Are you sure? I reproduced with Caret 1.9.1

**Comment by astoilkov** [comment] 2016-11-21 10:55
What is the difference that you see between a document with medium and small font size?

**Comment by instanceofme** [comment] 2016-11-21 17:41
Same as the files I uploaded above: a change in `rem` that causes a change in my line-height (and a lot of other things based on it in my theme), despite a `html { font-size: 18px !important; }` before.

**Comment by astoilkov** [comment] 2016-11-22 06:55
Can you send us your custom theme file so we could see what the problem is?

**Comment by instanceofme** [comment] 2016-11-22 08:35
- The markdown:

    ```markdown
    # Title
    
    Par1
    
    Par2
    ```

- [The theme](https://github.com/careteditor/caret/files/605841/Classic.css.zip)
- [2016-11-22.small.pdf](https://github.com/careteditor/caret/files/605842/2016-11-22.small.pdf)
- [2016-11-22.medium.pdf](https://github.com/careteditor/caret/files/605843/2016-11-22.medium.pdf)

**Comment by astoilkov** [comment] 2016-12-07 11:10
Hi @instanceofme,

In the next version release of Caret this issue will be fixed. Be aware of the fact that the `html { font-size: 18px !important; }` doesn't change the theme and its exporting in any way. You could remove that part from your theme. The thing that will make the printing consistent is the CSS below(which you already have in your theme).

```
@media print {
  .preview {
    font-size: 14px !important;
  }
}
```

P.S. Sorry for the big delay but this turned out to be a complicated problem. Because the preview is inside of a shadow DOM we had to manually loop through the CSS theme file to find any print selectors and cascade them to the `<head>` of the page.

**Comment by instanceofme** [comment] 2016-12-07 13:10
So this stille does not allow to use `rem`s, right? Since `rem` is relative to `html`'s font-size.

**Comment by astoilkov** [comment] 2016-12-07 13:20
What do you mean it doesn't allow you to use `rem`s?

You could use your `rem` units in the theme file and they will scale based on the app font size. However, if you want to make the printing consistent regarding of the current font size you could add the code provided above.

**Comment by instanceofme** [comment] 2016-12-07 14:01
Nice, then the `rem`s should work. I'll try that when you release it.

**Comment by astoilkov** [comment] 2016-12-08 15:32
We included the change in the latest Caret 1.11.0 release.

Could you test it and let me know if everything works correctly.

**Comment by astoilkov** [comment] 2017-01-17 12:39
Closing this issue as it seems resolved. Write here if you have any problems.

**Closed by astoilkov** 2017-01-17 12:39 UTC
Labels: enhancement

**Comment by instanceofme** [comment] 2017-01-18 10:27
Sorry I missed your previous message. Indeed it works with `rem` now.
