### ISSUE TITLE
1.2.2 always opens in dark mode

### ISSUE THREAD

**Issue by bellebethcooper** [careteditor/caret#65] opened 2016-04-19 04:13 UTC
I'm using version 1.2.2 on a Mac running OS X 10.11.4 and I've noticed every time I open Caret it has dark mode turned on, even if I had it turned off before quitting the app last time.

**Comment by erusev** [comment] 2016-04-19 06:48
@astoilkov I'm unable to reproduce this, but it could be related to caching as we changed the name of `night mode` to `dark mode`.

**Comment by bellebethcooper** [comment] 2016-04-19 07:36
Also noticed if I change the font size to big, it's back to medium next time I open Caret.

**Comment by erusev** [comment] 2016-04-19 12:26
@hkdobrev Can you see if you can reproduce this issue?

**Comment by hkdobrev** [comment] 2016-04-19 12:51
@erusev I can reliably reproduce the issue. I've tried playing with it, opening new windows, saving the file, then closing, opening a new instance of the app, the issue was always reproducing. Version 1.2.2 as well.

**Comment by erusev** [comment] 2016-04-19 13:39
Thanks, @hkdobrev, that's very helpful.

**Comment by erusev** [comment] 2016-04-19 14:18
@hkdobrev we need a bit more help - can zip the files at ~/Library/Application Support/Caret/caret and send it to me at hello@erusev.com so that we can investigate - we were not able to reproduce even in a virtual machine :(

**Comment by huwd** [comment] 2016-05-05 10:48
I've also got this issue, Ubuntu 16.04, what's worth sending you? `~/opt/caret`? Got the following in there:
```
  - after-install.tpl  
  - Caret
  - icudtl.dat    
  - libnode.so  
  - LICENSES.chromium.html  
  - natives_blob.bin  
  - snapshot_blob.bin
  - after-remove.tpl   
  - content_shell.pak  
  - libffmpeg.so  
  - LICENSE     
  - locales                 
  - resources         
  - version
```

**Comment by astoilkov** [comment] 2016-06-04 17:58
Hi,

This issue should be fixed in the latest Caret release. It would be awesome if anyone could verify that the problem is resolved.

Thanks!

**Comment by bellebethcooper** [comment] 2016-06-05 04:23
I can replicate this issue reliably in 1.3.1 with various Markdown files, sorry.

**Comment by huwd** [comment] 2016-06-10 10:10
Ok so good news-ish. Upgrade to version 1.3.2 it now remembers dark/light preference on ubuntu 16.04.

However the markdown preview pane (right) is permanently locked to light mode.

**Comment by erusev** [comment] 2016-06-10 22:53
> Upgrade to version 1.3.2 it now remembers dark/light preference on ubuntu 16.04.

Glad to hear that.

> However the markdown preview pane (right) is permanently locked to light mode.

This is intentional - the idea is that the appearance of the preview should be independent of the editor - we plan to add support for predefined themes, like GitHub, Medium, etc, as well as custom themes.

**Comment by huwd** [comment] 2016-06-19 12:52
I see - I guess custom CSS will fix that.

Aren't dark modes more often about usability than style though? Often I find there usage is about lighting conditions, outdoors or in blazing bright rooms I prefer to put light mode on and have my screen kick out more white - in a dark room for late night typing dark mode isn't such a shock to the eye.

So whilst i totally understand the idea that markdown should be kept to content, rendering to style... isn't there still a case for linking the two panes over how much light they throw at my eye?

**Comment by erusev** [comment] 2016-06-19 15:29
Sure, this makes a lot of sense, but what happens when we introduce preview themes? I imagine that we'd have preview themes like GitHub, Tumblr, Medium, etc. - would we have to have dark versions of them? What does the dark version of GitHub look like? How's it implemented? Is it 2 CSS files or is it some new format? There might be simple answers to these questions but I haven't found them :(

**Comment by huwd** [comment] 2016-06-19 16:09
Yeah fair enough, I think trying to design like github but dark - or playing with colour theory to make an invert, would be a total pain.

So... Dark/Light mode or Custom css will be the css applied just to the writing pane, and then preset GitHub, Tumblr, Medium or custom css will be separate files for the viewing pane?

Perhaps it's just me but I find it far more difficult to parse what I'm reading flicking between two panes with dramatically different background colours. May well just be me though!

I'll hang on for custom css. Thanks!

**Comment by astoilkov** [comment] 2016-08-01 14:16
Hey @bellebethcooper,

Hopefully one last try. Can you update to latest Caret version(1.5.2) and try if your settings will now persist. We changed the entire mechanism for saving settings so now everything should work correctly.

Thanks.

**Comment by bellebethcooper** [comment] 2016-08-02 03:12
@astoilkov Success! Thanks so much for your effort to fix this :)

**Comment by astoilkov** [comment] 2016-08-02 06:23
:tada: Awesome! Really happy we helped.

Have a great day.

**Closed by astoilkov** 2016-08-02 06:23 UTC
Labels: bug, resolved
