### ISSUE TITLE
Electron Memory Leak or Race Condition

### ISSUE THREAD

**Issue by OleVik** [careteditor/caret#74] opened 2016-06-05 11:58 UTC
After a clean installation of v.1.3.1 on Windows 10 x64, I launch Caret and switch to Light Mode. Then I attempted to type a few words, basically just "# Header" and the program became unresponsive. Half a minute later, the Electron-process was running upwards of 1500MB of memory and 50% of the CPU, halting itself and most all else. A bit hefty for a Markdown editor, no?

**Comment by erusev** [comment] 2016-06-05 13:21
@OleVik 

We'll investigate and get back to you.

We have a lot of things to polish in the Windows version. We plan to release a patch later next week. Meanwhile, any feedback is very welcome.

**Comment by erusev** [comment] 2016-06-05 13:24
One question regarding the issue:

Does the issue occur every time you switch to the light theme and type a few words?

Thanks.

**Comment by OleVik** [comment] 2016-06-05 21:05
Every time I type into the editor, at least attempt to type, the halt the occurs. I should note that this was when installed from the CaretSetup.exe.

**Comment by astoilkov** [comment] 2016-06-07 10:19
Hi @OleVik,

Apologies for the caused inconvenience. This issue is now fixed in the latest Caret release. You could head out to http://caret.io/ and download the latest version of Caret. Additionally, from now on the application will get updated automatically. Thanks for reporting this issue.

**Closed by astoilkov** 2016-06-07 10:19 UTC
Labels: bug
