### ISSUE TITLE
Links to md-files and pdf-files not working in Mac-version

### ISSUE THREAD

**Issue by reisixx** [careteditor/caret#703] opened 2018-03-28 15:49 UTC
These links work fine in the win-version, but they are not triggering any action on the Mac, although they are displayed as "active".

**Comment by astoilkov** [comment] 2018-03-29 07:32
Hi @reisixx,

This seems like a duplicate of https://github.com/careteditor/caret/issues/704. Is it possible to answer the questions there?

Thanks in advance.

I will close this issue so we can continue the discussion in the other issue.

**Closed as completed by astoilkov** 2018-03-29 07:32 UTC
