### ISSUE TITLE
Insert tab character?

### ISSUE THREAD

**Issue by gandalfsaxe** [careteditor/caret#776] opened 2018-07-07 09:23 UTC
How do you insert tab character at the cursor? The tab button just indents the whole line, which I don't want.

I'm having multiple lines of code and I'd like to line some elements (comments) up horizontally.

I really think that tab should just insert a tab character, and then another function / keyboad shortcut should indent the whole line.

**Comment by astoilkov** [comment] 2018-07-11 07:07
Hi @gandalfsaxe,

This is duplicate of https://github.com/careteditor/issues/issues/134.

I will close this issue in favor of the old one. You can write any further comments there. Thanks.

**Closed as completed by astoilkov** 2018-07-11 07:07 UTC
Labels: duplicate
