### ISSUE TITLE
Trying to use checkbox functionality similar to Github Flavored Markdown's "to do list" style checkboxes

### ISSUE THREAD

**Issue by ekillaby** [careteditor/caret#72] opened 2016-05-17 02:15 UTC
In Github we can do things like the following
```
[ ] My first task
[ ] My second task
[ ] My third task
```

In preview mode this displayed a checkbox and I tried to click the checkbox, which is when the error occurred.

The following error has occurred:
```
{
    "message": "Cannot read property 'nodes' of undefined",
    "version": "1.2.2",
    "platform": "darwin",
    "os": "15.3.0",
    "path": "web/Editor.Markdown.js",
    "code": "_0x3815xe=_0x3815x2[_0x27f9[61]][0],_0x3815xf=this[_0x27f9[0]][_0x27f9[62]](),_0x3815x10=this[_0x27f9[0]][_0x27f9[63]](_0x3815xe),_0x3815x11=-1!=_0x3815x10[_0x27f9[65]](_0x27f9[64])",
    "line": 5,
    "column": 7828,
    "stack": [
        "at Object.EditorMarkdown.(anonymous function).setTaskChecked (web/Editor.Markdown.js:5:7828)",
        "at MainView.caret.inherit._checkTaskList (packages/Preview/PreviewDesktop.js:5:3490)"
    ]
}
```

**Comment by erusev** [comment] 2016-05-17 07:59
This seems related to #70.

**Comment by astoilkov** [comment] 2016-06-04 19:27
Hi @ekillaby,

As the issue is duplicate of #70 I will close this one so it is easier for all of us to track.

**Closed by astoilkov** 2016-06-04 19:27 UTC
