### ISSUE TITLE
Double click selects wrong word

### ISSUE THREAD

**Issue by henrikstroem** [careteditor/caret#161] opened 2016-11-01 18:06 UTC
Double clicking a word doesn't select the word, but the next or next again word.

**Comment by erusev** [comment] 2016-11-01 19:55
Could you share OS and Caret version, also, can you reproduce this in a different text? Thanks

**Comment by henrikstroem** [comment] 2016-11-02 07:52
Caret 1.8.2
macOS 10.12.1 (16B2555)

After restarting Caret the problem is gone.

**Comment by erusev** [comment] 2016-11-02 08:08
Thanks, we'll invetigate

**Comment by astoilkov** [comment] 2016-11-21 08:20
We think we found the reason for the issue. This should be now resolved in the latest Caret release. It shouldn't happen any more.

Thanks for reporting. Closing this issue.

**Closed by astoilkov** 2016-11-21 08:20 UTC
Labels: bug, resolved
