### ISSUE TITLE
Click on title issue

### ISSUE THREAD

**Issue by nap** [careteditor/caret#76] opened 2016-06-06 17:43 UTC
When you click next (or on) to the title of the document you are working on, the application scroll down to what seems to be a random location in the document. Which make it weird if you just want to move the current window around.

**Comment by anandrajaram** [comment] 2016-06-06 17:56
+1 am having this too

**Comment by astoilkov** [comment] 2016-06-07 10:12
The issue is now fixed in the latest 1.3.2 Caret release. Thanks for reporting. Closing this.

**Closed by astoilkov** 2016-06-07 10:12 UTC
Labels: bug
