### ISSUE TITLE
Nested list bug: incorrect font used

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#451] opened 2017-07-21 12:18 UTC
![image](https://user-images.githubusercontent.com/101152/28463146-3ab577e0-6e1f-11e7-9575-af38d2da1c39.png)

The fenced code block is indented with 8 spaces, the next list item incorrectly uses a fixed width font.

**Comment by manuelbua** [comment] 2017-08-01 09:15
I would like to join this as well: i'm hitting the same problem as well as in the preview pane:
![listitems-incorrect-render](https://user-images.githubusercontent.com/819314/28817988-2371562e-76aa-11e7-9860-2a84900fc5f9.jpg)

This is a Pastie link with the Markdown source code that reproduce the problem quite clearly, in both the editor and in the preview pane: https://pastebin.com/45fHAX5A

Also note the preview pane shows a rectangular area around the code block that's wider and not indented as it should, looks like it is related to the issue #332 as well.

**Comment by manuelbua** [comment] 2017-08-01 09:23
While doing some tests i noticed it behaves quite correctly in the preview pane when indenting the backticks correctly, only the styling there is quite different, as in #332.

The editor font, however, remains wrong:
![listitems-incorrect-render-indented-backticks](https://user-images.githubusercontent.com/819314/28818616-e2dc5f3a-76ab-11e7-9930-03b41a2e1fa4.jpg)

**Comment by astoilkov** [comment] 2018-01-05 15:41
This issue is fixed in [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue.

**Closed by astoilkov** 2018-01-05 15:41 UTC
Labels: bug, resolved
