### ISSUE TITLE
Sidebar covers content

### ISSUE THREAD

**Issue by flegfleg** [careteditor/caret#438] opened 2017-07-12 07:40 UTC
![bildschirmfoto 2017-07-12 um 09 30 19](https://user-images.githubusercontent.com/4009931/28106728-43dd2bb0-66e5-11e7-9547-b7ee1281ae1e.png)

* In macOS, the default behavior would be to expand the window size or resize the main content area. Expected behavior: Hit `Command+2`, sidebar is opened, window resized. 
* Shortcut `Command+2` to toggle the sidebar is buggy (dependent on the focus?) 
  * Hit `Command+2` (no sidebar)
  * Click into Editor (sidebar appears)
  * Hit `Command+2` (sidebar stays open)
  * Click into sidebar, hit `Command+2` (sidebar is hidden)

Caret 3.0.2

**Comment by astoilkov** [comment] 2017-07-12 10:20
Hi @flegfleg,

> - In macOS, the default behavior would be to expand the window size or resize the main content area. Expected behavior: Hit Command+2, sidebar is opened, window resized.

We actually borrowed a behavior from the Calendar app which indeed triggers window resize when there is enough space for the window to be resized but floats that window when there isn't. We don't automatically resize the window because we feel that it is your decision to make and want to allow users to use sidebars while they have smaller windows.

> Shortcut Command+2 to toggle the sidebar is buggy (dependent on the focus?)
> - Hit Command+2 (no sidebar)
> - Click into Editor (sidebar appears)
> - Hit Command+2 (sidebar stays open)
> - Click into sidebar, hit Command+2 (sidebar is hidden)

Thanks for reporting this problem. We actually fixed this in the latest 3.2.1 release. You could check it out and let me know.

Im closing this issue. If the issue is not fixed for your in 3.2.1 please let me know so we could reopen the issue and investigate.

**Closed by astoilkov** 2017-07-12 10:20 UTC
Labels: bug, resolved
