### ISSUE TITLE
Mouse offset issues in Win7

### ISSUE THREAD

**Issue by ianaf100** [careteditor/caret#354] opened 2017-05-10 00:02 UTC
Occasionally I have been experiencing some offset between my mouse cursor and the actual selection. It seems to happen randomly, sometimes it is a pretty significant offset, sometimes subtle. It usually is fixed by restarting caret or toggling preview, but it tends to come back.

I made a quick gif to show this:

![2017-05-09_17-53-39](https://cloud.githubusercontent.com/assets/26445169/25877450/c229e5e4-34e0-11e7-8612-15b165b4c848.gif)

I am using Windows 7 64 bit

**Comment by astoilkov** [comment] 2017-05-10 06:18
We will investigate. Thanks for reporting.

**Comment by manuelbua** [comment] 2017-05-10 08:21
This actually happened to me as well, on my ArchLinux machine: i'll try to reproduce as well and report back.

**Comment by manuelbua** [comment] 2017-05-10 08:28
I can reproduce it most of the times by opening Caret editor, doing <kbd>CTRL+N</kbd> to create a new file, then dropping the attached `readme.md` file will cause Caret to offset the cursor point when clicking.

The file is actually a Markdown text file, but couldn't upload with that extension.

Unfortunately this isn't much consistent, but it's the only text file it will show that strange behavior.

[README.txt](https://github.com/careteditor/caret/files/989164/README.txt)

**Comment by pslobo** [comment] 2017-05-10 09:53
I've seen this happen once and have never again been able to reproduce consistently on the Mac. Performing the steps described by @manuelbua doesn't replicate the behaviour for me.

**Comment by kochie** [comment] 2017-05-12 13:31
I've had it happen on Arch Linux as well. Especially noticable when using tables.

**Comment by astoilkov** [comment] 2018-01-11 14:17
We have found the cause of the problem and fixed it in the new Caret 4.0 Beta available [here](https://caret.io/4beta/).

Closing this issue. Thanks for all the information provided.

**Closed by astoilkov** 2018-01-11 14:17 UTC
Labels: bug, resolved
