### ISSUE TITLE
Error occured when editing.

### ISSUE THREAD

**Issue by TheNetAdmin** [careteditor/caret#501] opened 2017-08-15 08:40 UTC
The following error has occurred:
```
{
    "message": "Cannot read property 'type' of undefined",
    "version": "3.4.3",
    "os": "Windows 10",
    "path": "C:\\Users\\MATRIX\\AppData\\Local\\Caret\\app-3.4.3\\resources\\app.asar\\extensions\\Path\\PathWrap.js",
    "code": "(t[0].text=\"...\",!0):(\"separator\"!=r.type",
    "line": 5,
    "column": 1389,
    "stack": [
        "at t.value ((C:\\Users\\MATRIX\\AppData\\Local\\Caret\\app-3.4.3\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:1389)",
        "at t.value ((C:\\Users\\MATRIX\\AppData\\Local\\Caret\\app-3.4.3\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:1098)",
        "at t.value ((C:\\Users\\MATRIX\\AppData\\Local\\Caret\\app-3.4.3\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:888)",
        "at t.value ((C:\\Users\\MATRIX\\AppData\\Local\\Caret\\app-3.4.3\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:704)",
        "at t.value ((C:\\Users\\MATRIX\\AppData\\Local\\Caret\\app-3.4.3\\resources\\app.asar\\extensions\\Title.js:5:1724)",
        "at t.value ((C:\\Users\\MATRIX\\AppData\\Local\\Caret\\app-3.4.3\\resources\\app.asar\\web\\Events.js:5:1335)",
        "at t.value ((C:\\Users\\MATRIX\\AppData\\Local\\Car

**Comment by astoilkov** [comment] 2017-08-15 08:45
Hi @TheNetAdmin,

This seems to be a duplicate of https://github.com/careteditor/caret/issues/493. I will close this issue in favor of https://github.com/careteditor/caret/issues/493. You could track the issue progress there.

Thanks for reporting!

**Closed by astoilkov** 2017-08-15 08:45 UTC
Labels: duplicate
