### ISSUE TITLE
Preview Themes not available (V4 beta)

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#629] opened 2018-01-28 06:37 UTC
Looking under View > Preview Theme I see no themes. Clicking on Add Themes seems to open the theme folder with 3 premade themes in the folder which are not showing up in the app.

**Comment by netmasteroc3** [comment] 2018-01-30 03:07
I'm having the same problem. None of the preview themes show up including my custom one.

Win 10 Build 1709
Caret 4 Beta 8

**Comment by astoilkov** [comment] 2018-01-31 10:22
Until we fix this a workaround for the issue is opening the preview and then going to `View -> Preview Themes`.

**Comment by netmasteroc3** [comment] 2018-01-31 19:33
@astoilkov 

Even in preview mode, none of my themes are listed in the menu.

**Comment by ramthir** [comment] 2018-02-16 07:10
I have the same issue with 4.0 beta 8. Can't get the Themes to list either in editor or preview mode.
 
![Caret Beta Themes](https://user-images.githubusercontent.com/11470503/36296949-eac867a0-1315-11e8-9334-1fd2c2a59d5d.png)

**Comment by astoilkov** [comment] 2018-03-19 13:19
This is now fixed in the latest update of Caret Beta.

Closing this issue. Thanks for reporting.

**Closed as completed by astoilkov** 2018-03-19 13:19 UTC
Labels: bug, resolved

**Comment by netmasteroc3** [comment] 2018-03-19 23:34
I'm still seeing this problem in Caret Beta 4 RC1 (Win 10 x64 build 1709).

I even uninstalled caret, cleaned out all the caret beta folders in App Data, and reinstalled it from a fresh download.

**Comment by astoilkov** [comment] 2018-03-20 09:03
@netmasteroc3 Under Windows we had another bug which caused the same behavior. This is now fixed in the Caret Beta RC2 update. Sorry for the inconvenience.
