### ISSUE TITLE
Exception when starting up Caret

### ISSUE THREAD

**Issue by dracan** [careteditor/caret#493] opened 2017-08-10 06:18 UTC
This just happened when starting up Caret.

The following error has occurred:
```
{
    "message": "Cannot read property 'type' of undefined",
    "version": "3.4.2",
    "os": "Windows 10",
    "path": "C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.2\\resources\\app.asar\\extensions\\Path\\PathWrap.js",
    "code": "(t[0].text=\"...\",!0):(\"separator\"!=r.type",
    "line": 5,
    "column": 1389,
    "stack": [
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.2\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:1389)",
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.2\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:1098)",
        "at t.value ((C:\\Users\\Dan\\AppData\\Local\\Caret\\app-3.4.2\\resources\\app.asar\\extensions\\Path\\PathWrap.js:5:888)"
    ]
}
```

**Comment by dracan** [comment] 2017-08-10 06:21
It actually does this every time I start up Caret now.

**Comment by dracan** [comment] 2017-08-10 06:31
Got rid of the error by deleting the various cache folders from my %appdata%\caret folder.

**Comment by dracan** [comment] 2017-08-10 06:31
Oh, no - that wasn't true. It's just come back :(

**Comment by astoilkov** [comment] 2017-08-10 07:41
This is some kind of combination between the file path and the windows size. Can you make a screenshot of the file path and the window size?

**Comment by dracan** [comment] 2017-08-10 13:36
Doesn't seem to be doing it now I'm afraid. Seems a very odd combination of two (what should be) completely unrelated things to cause an exception though :-|

**Comment by astoilkov** [comment] 2017-08-10 16:13
The failing code is related to the wrapping of the file path in the title bar when there is not enough space for the entire path.

We resolved the issue in the latest version of Caret.

Closing this issue. Thanks for reporting.

**Comment by dracan** [comment] 2017-08-10 16:21
Ah, that makes sense. Thanks for the very quick fix :)

**Comment by dracan** [comment] 2017-08-14 12:13
What version was this fixed in? I've got 3.4.3, and still get the same issue. It's exactly the same error and stacktrace (except for the version number in the paths of course).

**Comment by astoilkov** [comment] 2017-08-14 12:17
I am reopening this issue then. When we fixed this issue we guessed what the problem is because we weren't able to reproduce it. It seems we haven't fixed it after all. If you somehow understand the replication steps please let us know.

**Comment by dracan** [comment] 2017-08-14 12:22
I don't I'm afraid. It happens when I switch to side by side view (ie. Ctrl r). When I get it, the path at the top disappears, and there's also a gap at the top of the editor window. I cant at the moment, but will attach some screenshots this evening.

**Comment by dracan** [comment] 2017-08-14 12:24
I'll also try later, instead of switching to side by side view, I'll try resizing the window width (so editor width is the same as it would be in side by side view).

**Comment by dracan** [comment] 2017-08-14 19:10
I can't reproduce by resizing the window - it just happens when my Caret window is full screen, and I put into side-by-side view.

It still happens if I remove all the text (which I've done for the screenshot below). Hopefully if you force the same same dimensions as my screenshot, you may be able to replicate it ¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/567988/29286918-a538ad2a-812b-11e7-8634-05773935e42c.png)

Here's also the relative path I'm using ...

![image](https://user-images.githubusercontent.com/567988/29286978-d8add87e-812b-11e7-86ac-ded1137da170.png)

And if it helps, here's the absolute path: `C:\Users\Dan\Dropbox\Apps\DanClarkeBlog\2017-08-PassionForDev\post.md`.

It's also perhaps worth pointing out that I'm on a MacBook Pro (bootcamped with Win10). So it's high res display with 200% scaling.

![image](https://user-images.githubusercontent.com/567988/29287188-8047093e-812c-11e7-80b8-ce5cec5ffba2.png)

**Comment by dracan** [comment] 2017-08-15 11:28
I actually only seem to get this on my macbook screen which uses this high resolution display (eg. 2x scaling). If I move to another monitor, it doesn't error. Although this might be a resolution thing rather than a scaling thing.

@TheNetAdmin - are you using a high resolution display?

**Comment by TheNetAdmin** [comment] 2017-08-15 11:45
@dracan Yeah, I'm using surface pro 4, with 1.5x scaling I believe.

_Sent from my Sony F8332 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dracan** [comment] 2017-08-16 16:46
@astoilkov Just noticed you've added the resolved label. Does this mean you've fixed it? Is there an ETA for this to be released, as I'm currently having to use another Markdown editor until this is fixed. Will be good to get back to Caret :)

**Comment by astoilkov** [comment] 2017-08-17 07:28
@dracan Yes. I am pretty confident we fixed the problem. We will publish the next release tomorrow or early next week. Sorry for the inconvenience.

**Comment by dracan** [comment] 2017-08-21 18:45
@astoilkov Is there any further news on when this will be released? I'm quite surprised that bug like this hasn't been pushed out as high priority to be honest. Especially as this isn't a free open source project - it's a product that customers have purchased.

**Comment by astoilkov** [comment] 2017-08-22 07:39
@dracan Caret 3.4.4 with the fix included is now available. Sorry for the delay. You are absolutely correct. This is a mistake from our side. We were really concentrated in the next 3.5 release which turned out to be very hard technical challenge.

Please let me know if the new release fixes the problem.

**Comment by dracan** [comment] 2017-08-22 07:52
Awesome! I can confirm that that appears to have fixed the issue! 😄

**Comment by astoilkov** [comment] 2017-08-22 07:53
Great to hear that. I am closing this issue then.

**Closed by astoilkov** 2017-08-22 07:53 UTC
Labels: bug, resolved

**Comment by dracan** [comment] 2017-08-22 07:56
Looks like I spoke too soon :( This time a slightly different exception. See issue 511.
