### ISSUE TITLE
PDF support for images

### ISSUE THREAD

**Issue by gandalfsaxe** [careteditor/caret#580] opened 2017-12-05 22:21 UTC
As far as I can see, PDF images, i.e. `![Caption](somefig.pdf)`, doesn't show up as images either in the editor preview or the View->Preview. It would be nice with support for PDF images.

**Comment by astoilkov** [comment] 2017-12-06 06:58
This seems to be a duplicate of https://github.com/careteditor/caret/issues/530. I am closing this one in favor of the first opened issue.

**Closed as completed by astoilkov** 2017-12-06 06:58 UTC
