### ISSUE TITLE
Table renders incorrectly in PDF

### ISSUE THREAD

**Issue by tamagokun** [careteditor/caret#206] opened 2016-12-21 15:57 UTC
Exporting a document to PDF that contains a table does not render correctly.

It looks like whatever page the table is on will double render the first row or header row at the top of the page.

![screen shot 2016-12-21 at 10 54 54 am](https://cloud.githubusercontent.com/assets/487333/21395881/36e62ccc-c76c-11e6-8db6-9967f3651117.png)

**Comment by astoilkov** [comment] 2016-12-21 15:59
Hi @tamagokun,

We are are aware of the issue. You could read more about it [here](https://github.com/careteditor/caret/issues/132#issuecomment-251406895).

Closing this issue as it is a duplicate of an existing one.

**Closed by astoilkov** 2016-12-21 15:59 UTC
Labels: duplicate

**Comment by tamagokun** [comment] 2016-12-21 16:17
Darn! I even did due diligence and looked through the issues before posting. Thank you! Just started using Caret, and really love it.
