### ISSUE TITLE
Table Bug in PDF Export

### ISSUE THREAD

**Issue by dwagnerkc** [careteditor/caret#132] opened 2016-10-04 13:09 UTC
_Slick editor guys. Hope this is the right place to report a bug. Thanks, David._

When exporting to PDF with tables after the first page the column headers appear at the top of the page over any other text. 

![image](https://cloud.githubusercontent.com/assets/4469300/19075151/3e1cc4a6-8a09-11e6-9688-14f1f5873067.png)

**Details**
Caret 1.7.0
OS X El Capitan 10.11.6
Default and custom CSS themes
Only on PDF Export not in Preview 

Screenshot of correct Preview window below and the full exported PDF below as well.

![image](https://cloud.githubusercontent.com/assets/4469300/19075190/6a8b34e6-8a09-11e6-92ae-a4a076b17b98.png)

[CaretPDFExport.pdf](https://github.com/careteditor/caret/files/508482/CaretPDFExport.pdf)

**Comment by astoilkov** [comment] 2016-10-04 14:36
Hi @dwagnerkc,

This seems to be a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=631222). It is already fixed and it will ship in Chrome 54 which is few weeks from now. When this happens we will update our app and create a new release to fix this issue.

Thanks for reporting.

**Comment by dwagnerkc** [comment] 2016-10-04 14:47
Not only a quick reply, but you also found the solution quickly! 👍  If you knew a work around in the meantime I would be all ears, but don't worry about it if not. Thank you!

**Comment by astoilkov** [comment] 2016-10-04 14:52
I have experimented with it and it seems there isn't an obvious workaround. I have tried applying CSS properties but without success. No information in the Chromium bug page either.

**Comment by dwagnerkc** [comment] 2016-10-04 14:52
That's fine. Thanks for taking a look. Appreciate your work.

**Comment by nio101** [comment] 2016-10-27 08:03
just FYI, this bug is still there in the 1.8.0 release...

**Comment by astoilkov** [comment] 2016-10-27 08:07
Yes. Indeed. We are waiting for Chromium to fix it and then we can update our app.

**Comment by czorzenone** [comment] 2016-12-05 16:16
This bug is still there in the 1.10.0 release on Windows 10.

**Comment by DCRichards** [comment] 2017-01-27 11:09
I'm still seeing this in 1.13.4 for MacOS, The chromium bug is marked as fixed now, any news on this?

**Comment by DCRichards** [comment] 2017-01-27 11:10
Interestingly, it doesn't appear to happen with the `Default` markdown preview setting, only `GitHub`

**Comment by astoilkov** [comment] 2017-01-27 19:37
Hi @DCRichards,

You are correct. The chromium bug is fixed and available in the latest version of Chrome. However, we depend on the [Electron](http://electron.atom.io/) project which haven't updated the version of Chrome in a while - they have some problems because Chrome build system changed in the last release of Chrome. Until Electron releases a version including the new version of Chrome we can't do anything about this.

Sorry for the inconvenience.

P.S. The issue appears in all themes. It is possible you got confused because the bug doesn't appear if you have only one page PDF.

**Comment by astoilkov** [comment] 2017-02-07 13:45
We are really happy to say that the issue is now resolved in the latest Caret 1.14.0 release. We apologize for the big delay but we weren't in control of it.

You could test it and write if you see any problems. Thanks for your patience.

Closing this issue.

**Closed by astoilkov** 2017-02-07 13:45 UTC
Labels: bug, resolved
