### ISSUE TITLE
Support YAML front matter

### ISSUE THREAD

**Issue by ihackalot** [careteditor/caret#173] opened 2016-11-17 15:10 UTC
It would be nice if Caret could detect YAML front matter... Useful if you use it with Jekyll and similar.

**Comment by erusev** [comment] 2016-11-18 12:00
Yes, this is definitely something we want to include.

**Comment by astoilkov** [comment] 2016-11-21 08:57
This issue is actually a duplicate of https://github.com/careteditor/caret/issues/49.

I will close this issue and leave the older one for comments and status updates.

**Closed by astoilkov** 2016-11-21 08:57 UTC
