### ISSUE TITLE
No smooth scrolling using a Windows Precision Touchpad

### ISSUE THREAD

**Issue by jsmolka** [careteditor/caret#745] opened 2018-05-14 08:52 UTC
I am currently using Caret 3.4.6 on my Dell XPS 13 with a Windows Precision Touchpad. When I start Caret, scrolling a through file is really unresponsive and laggy. After switching from fullscreen to windowed mode or vise versa the bug disappears and scrolling becomes smooth again. I have tried using the beta version but the bug still persists.

I have googled a bit and found a simular [issue](https://github.com/electron/electron/issues/8960) in Electron which has been fixed recently.

**Comment by astoilkov** [comment] 2018-05-15 16:52
Hi @jsmolka,

Yes. You are correct. The next Caret Beta will include the fix from Electron.

As this issue is duplicate of https://github.com/careteditor/caret/issues/276 I will close this one. You could subscribe to the other issue to get notified when we release the next update.

**Closed as completed by astoilkov** 2018-05-15 16:52 UTC
Labels: bug, duplicate
