### ISSUE TITLE
Autocorrect feedback

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#185] opened 2016-12-09 12:50 UTC
I noticed that 1.11 started auto-correcting misspelled words. Two pieces of feedback:

1. I turned it on and then quickly back off on a certain document, but I still get autocorrections. Maybe I need to reopen the document?
2. This is a tricky feature to have because some auto-corrections might be false positives. There should be a clear visual clue for a couple of seconds that the automatic change happened, and a quick way to revert it if it was done by mistake. I think MS Office does something like that with a tiny dropdown arrows next to auto-corrected words (though I generally disable auto-correcting in Word etc.).

**Comment by borekb** [comment] 2016-12-09 15:08
@erusev I see if for about a half a second, and it's subtle which is both good and dangerous :) But I liked autocorrect when it worked. Still, I personally prefer to have this feature turned off and I don't seem to be able to achieve that, it is always on.

**Comment by erusev** [comment] 2016-12-09 15:14
> Still, I personally prefer to have this feature turned off and I don't seem to be able to achieve that, it is always on.

I understand, I'm the same way, we'll fix that.

**Comment by sguergachi** [comment] 2016-12-11 21:01
I think for one, you should be able to undo the auto correct. As of now if I type "helo" it corrects to "hello" but if I undo it doesn't revert back to "helo" it reverts back to "" (removes the string completely). So the auto correction could be saved as an undo step of its own as a quick way to revert any corrections? Just an idea.

**Comment by erusev** [comment] 2016-12-11 21:32
@sguergachi I agree, we'll see what we can do.

**Comment by astoilkov** [comment] 2016-12-12 12:39
The issue is not fixed in the latest Caret 1.11.1 release.

Additionally, per @sguergachi request we implemented a undo checkpoint for every auto correction that happens.

**Closed by astoilkov** 2016-12-12 12:39 UTC
Labels: bug, resolved
