### ISSUE TITLE
Cannot read files from OneDrive with File On-Demand on Win10 Fall Creators Update

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#558] opened 2017-10-18 15:26 UTC
Windows Fall Creators Update (1709) arrived today with OneDrive's ["files on demand"](http://www.techrepublic.com/article/windows-10-fall-creators-update-how-to-use-onedrive-files-on-demand/). After this update, I cannot open any file from my OneDrive folder in Caret, via Ctrl+T, Ctrl+E, File > Open or drag & drop; all I see is this sad empty window:

![image](https://user-images.githubusercontent.com/101152/31726935-91ad6ca2-b428-11e7-8f6d-5f9395e715b0.png)

I'm still trying to investigate this but so far, this is what I gathered:

- When I copy a file e.g. to my desktop, Caret opens it fine. 
- Other apps open my OneDrives files fine as well. I've tried Electron apps (VSCode) and Win32 apps (Notepad++), all works fine.
- The content is on the disk:

![image](https://user-images.githubusercontent.com/101152/31727172-3b5a2272-b429-11e7-8cce-9fb8e8539155.png)

![image](https://user-images.githubusercontent.com/101152/31727275-76e19352-b429-11e7-80da-7b70d78872a0.png)

**Comment by borekb** [comment] 2017-10-21 08:04
I can now reproduce on another computer that upgraded OneDrive tonight. It really seems to be about OneDrive, not the newer version of Windows.

**Comment by borekb** [comment] 2017-10-23 07:02
Some more details:

It's definitely Files On-Demand. I turned it off and Caret works fine again.

![image](https://user-images.githubusercontent.com/101152/31875914-7301d152-b7d0-11e7-8c59-99065f077a25.png)

With "Files On-Demand" turned on, the attribute in file properties > Details > Attributes is `ALP`.

- A = Archive
- L = Symbolic link / Junction / Mount point / has a reparse point
- P = Sparse file

[Source](https://superuser.com/a/982721/5872)

I'm not sure what they mean but I would suspect the "L" attribute is causing issues as I've seen Caret not handling symlinks properly on Windows in the past.

**Comment by astoilkov** [comment] 2017-10-23 07:49
@borekb - Thanks for the detailed information. We are starting to investigate the problem.

**Comment by f8ttyc8t** [comment] 2017-11-24 07:07
Hi @astoilkov ,
any idea when we can expect new version?
I'm using OneDrive on a daily basis, so this fix is crucial for me.

Thanks!

**Comment by astoilkov** [comment] 2017-11-24 08:46
Hi @f8ttyc8t,

It will take us between one and two weeks to release the new version.

**Comment by f8ttyc8t** [comment] 2017-11-24 08:51
HI @astoilkov,
Thanks! - will this be same version as mentioned [here](https://github.com/careteditor/caret/issues/560#issuecomment-343689554)?

**Comment by astoilkov** [comment] 2017-11-24 08:52
Yes

**Comment by f8ttyc8t** [comment] 2018-01-04 08:05
Hi @astoilkov,
you mentioned 3rd of January as date for beta [here](https://github.com/careteditor/caret/issues/588#event-1405093911). 

How do I get the beta?

Thanks

**Comment by erusev** [comment] 2018-01-04 10:39
@f8ttyc8t 

We just introduced it at https://twitter.com/careteditor/status/948861459785711617

**Comment by f8ttyc8t** [comment] 2018-01-04 12:27
@erusev 
Thanks for quick response!

**Comment by astoilkov** [comment] 2018-01-05 11:37
Is the issue fixed for you in the new 4.0 Beta release?

**Comment by borekb** [comment] 2018-01-05 13:42
I stopped using OneDrive, "unfortunately" 😀.

**Comment by f8ttyc8t** [comment] 2018-01-05 14:29
Can't verify it yet due to problems (caret beta0/1 is slow, locks up during startup, produces errors... will wait some time to give it a last chance).

**Comment by f8ttyc8t** [comment] 2018-01-05 19:53
About using beta in Windows 10:
Do I have to uninstall release version (3.x) of Caret before using beta version (4.0)?
Maybe slow caret beta response is because of having both versions installed?

**Comment by astoilkov** [comment] 2018-01-06 17:07
Hi @f8ttyc8t,

Can you describe more what do you mean by "slow response"?

We have made a new `caret-4.0.0-beta2` update. You can check out if it fixes the issues. Note that the first time you update to `caret-4.0.0-beta2` it still can cause some problems but after restarting the app (or the computer) the issues should be fixed.

**Comment by f8ttyc8t** [comment] 2018-01-08 07:34
Hi @astoilkov,
updated to beta2 and rebooted - helped.

@slow response: starting app (causing auto-loading a 17kb file) lasted approx. 25 seconds on my Win 10 machine (16GB, intel i7, SSD).

**Comment by astoilkov** [comment] 2018-01-08 14:07
@f8ttyc8t The slow performance could be caused by this [issue](https://github.com/careteditor/caret/issues/599) which we are working on. However, if your file doesn't contain nested blocks you could send it to contact@caret.io so we could debug it and find out what is the problem.

Thanks in advance.

**Comment by f8ttyc8t** [comment] 2018-01-08 14:58
@astoilkov slow performance has been fixed by beta 2 and reboot.
Now it's pretty fast (1-2 seconds).

 Good job!

**Comment by astoilkov** [comment] 2018-01-08 15:00
Great to hear that.

Closing this issue than. Feel free to open new issues for problems you discover.

Have a great day.

**Closed as completed by astoilkov** 2018-01-08 15:00 UTC
Labels: bug, resolved
